import { z } from "zod"

import GAME from "./game"
import { pokemonCardSchema, pokemonCardSchemaWithoutId, PokemonCardWithoutId, PokemonType } from "./pokemon"
import { yuGiOhCardSchema, yuGiOhCardSchemaWithoutId, YuGiOhCardWithoutId } from "./yu-gi-oh"

export const deleteOrUpdateCardRequestSchema = z.union([yuGiOhCardSchema, pokemonCardSchema])

export const createCardRequestSchema = z.union([yuGiOhCardSchemaWithoutId, pokemonCardSchemaWithoutId])

// Deleting and Updating a card requires an id field
export type DeleteOrUpdateCardRequest = z.infer<typeof deleteOrUpdateCardRequestSchema>

// CreateCard doesn't have an id field because it will be generated by the server
export type CreateCardRequest = z.infer<typeof createCardRequestSchema>

export const defaultValuesCreateCardRequest = (game: GAME): CreateCardRequest => {
    switch (game) {
        case GAME.YU_GI_OH:
            return {
                game: GAME.YU_GI_OH,
                name: "",
                img: "",
                attack: 0,
                defense: 0,
            } satisfies YuGiOhCardWithoutId
        case GAME.POKEMON:
            return {
                game: GAME.POKEMON,
                name: "",
                img: "",
                type: PokemonType.Normal,
            } satisfies PokemonCardWithoutId
        default:
            throw new Error("Invalid game type")
    }
}
