import type { Trade } from "@/types/finance/trade"

// eslint-disable-next-line import/prefer-default-export
export const trades: Trade[] = [
    {
        buyToClose: 0,
        contracts: 5,
        date: "2024-11-15",
        id: "1",
        profitLoss: 266.61,
        profitLossPercentage: 100.0,
        realized: "GAIN",
        sellToOpen: 53.32,
        strike: 146,
        ticker: "NVDA",
        type: "SELL_CALL",
    },
    {
        buyToClose: 0,
        contracts: 3,
        date: "2024-11-08",
        id: "2",
        profitLoss: 151.05,
        profitLossPercentage: 100.0,
        realized: "GAIN",
        sellToOpen: 50.35,
        strike: 146,
        ticker: "NVDA",
        type: "SELL_CALL",
    },
    {
        buyToClose: 0,
        contracts: 1,
        date: "2024-11-08",
        id: "3",
        profitLoss: 136.35,
        profitLossPercentage: 100.0,
        realized: "GAIN",
        sellToOpen: 45.45,
        strike: 230,
        ticker: "COIN",
        type: "SELL_CALL",
    },
    {
        buyToClose: 0,
        contracts: 1,
        date: "2024-11-08",
        id: "4",
        profitLoss: 125.35,
        profitLossPercentage: 100.0,
        realized: "GAIN",
        sellToOpen: 125.35,
        strike: 280,
        ticker: "TSLA",
        type: "SELL_CALL",
    },
    {
        buyToClose: 0,
        contracts: 3,
        date: "2024-11-01",
        id: "5",
        profitLoss: 135.96,
        profitLossPercentage: 100.0,
        realized: "GAIN",
        sellToOpen: 45.32,
        strike: 146,
        ticker: "NVDA",
        type: "SELL_CALL",
    },
    {
        buyToClose: 1.67,
        contracts: 3,
        date: "2024-11-01",
        id: "6",
        profitLoss: 214.93,
        profitLossPercentage: 97.72,
        realized: "GAIN",
        sellToOpen: 73.32,
        strike: 180,
        ticker: "AMD",
        type: "SELL_CALL",
    },
    {
        buyToClose: 0,
        contracts: 1,
        date: "2024-11-01",
        id: "7",
        profitLoss: 137.31,
        profitLossPercentage: 100.0,
        realized: "GAIN",
        sellToOpen: 137.31,
        strike: 280,
        ticker: "TSLA",
        type: "SELL_CALL",
    },
    {
        buyToClose: 0,
        contracts: 3,
        date: "2024-10-25",
        id: "8",
        profitLoss: 129.96,
        profitLossPercentage: 100.0,
        realized: "GAIN",
        sellToOpen: 43.32,
        strike: 145,
        ticker: "NVDA",
        type: "SELL_CALL",
    },
    {
        buyToClose: 0,
        contracts: 10,
        date: "2024-10-25",
        id: "9",
        profitLoss: 73.21,
        profitLossPercentage: 100.0,
        realized: "GAIN",
        sellToOpen: 7.321,
        strike: 23,
        ticker: "INTC",
        type: "SELL_CALL",
    },
    {
        buyToClose: 0,
        contracts: 3,
        date: "2024-10-18",
        id: "10",
        profitLoss: 162.96,
        profitLossPercentage: 100.0,
        realized: "GAIN",
        sellToOpen: 54.32,
        strike: 146,
        ticker: "NVDA",
        type: "SELL_CALL",
    },
    {
        buyToClose: 0,
        contracts: 10,
        date: "2024-10-18",
        id: "11",
        profitLoss: 313.21,
        profitLossPercentage: 100.0,
        realized: "GAIN",
        sellToOpen: 31.321,
        strike: 23,
        ticker: "INTC",
        type: "SELL_PUT",
    },
    {
        buyToClose: 0,
        contracts: 3,
        date: "2024-10-11",
        id: "12",
        profitLoss: 189.96,
        profitLossPercentage: 100.0,
        realized: "GAIN",
        sellToOpen: 63.32,
        strike: 185,
        ticker: "AMD",
        type: "SELL_CALL",
    },
    {
        buyToClose: 0,
        contracts: 3,
        date: "2024-10-11",
        id: "13",
        profitLoss: 183.96,
        profitLossPercentage: 100.0,
        realized: "GAIN",
        sellToOpen: 61.32,
        strike: 137,
        ticker: "NVDA",
        type: "SELL_CALL",
    },
    {
        buyToClose: 0,
        contracts: 1,
        date: "2024-10-11",
        id: "14",
        profitLoss: 319.31,
        profitLossPercentage: 100.0,
        realized: "GAIN",
        sellToOpen: 319.31,
        strike: 225,
        ticker: "TSLA",
        type: "SELL_PUT",
    },
    {
        buyToClose: 2.68,
        contracts: 2,
        date: "2024-10-04",
        id: "15",
        profitLoss: 251.27,
        profitLossPercentage: 97.91,
        realized: "GAIN",
        sellToOpen: 128.31,
        strike: 290,
        ticker: "TSLA",
        type: "SELL_CALL",
    },
    {
        buyToClose: 2.68,
        contracts: 1,
        date: "2024-10-04",
        id: "16",
        profitLoss: 116.63,
        profitLossPercentage: 97.75,
        realized: "GAIN",
        sellToOpen: 119.31,
        strike: 215,
        ticker: "COIN",
        type: "SELL_CALL",
    },
    {
        buyToClose: 0,
        contracts: 3,
        date: "2024-10-04",
        id: "17",
        profitLoss: 51.96,
        profitLossPercentage: 100.0,
        realized: "GAIN",
        sellToOpen: 17.32,
        strike: 175,
        ticker: "AMD",
        type: "SELL_CALL",
    },
    {
        buyToClose: 0,
        contracts: 3,
        date: "2024-05-24",
        id: "18",
        profitLoss: 207.96,
        profitLossPercentage: 100.0,
        realized: "GAIN",
        sellToOpen: 69.32,
        strike: 185,
        ticker: "AMD",
        type: "SELL_CALL",
    },
    {
        buyToClose: 1.67,
        contracts: 3,
        date: "2024-06-07",
        id: "19",
        profitLoss: 228.92,
        profitLossPercentage: 97.85,
        realized: "GAIN",
        sellToOpen: 77.98,
        strike: 190,
        ticker: "AMD",
        type: "SELL_CALL",
    },
    {
        buyToClose: 0,
        contracts: 3,
        date: "2024-06-14",
        id: "20",
        profitLoss: 165.96,
        profitLossPercentage: 100.0,
        realized: "GAIN",
        sellToOpen: 55.32,
        strike: 185,
        ticker: "AMD",
        type: "SELL_CALL",
    },
    {
        buyToClose: 0,
        contracts: 3,
        date: "2024-06-28",
        id: "21",
        profitLoss: 120.96,
        profitLossPercentage: 100.0,
        realized: "GAIN",
        sellToOpen: 40.32,
        strike: 185,
        ticker: "AMD",
        type: "SELL_CALL",
    },
    {
        buyToClose: 0,
        contracts: 3,
        date: "2024-07-12",
        id: "22",
        profitLoss: 150.96,
        profitLossPercentage: 100.0,
        realized: "GAIN",
        sellToOpen: 50.32,
        strike: 195,
        ticker: "AMD",
        type: "SELL_CALL",
    },
    {
        buyToClose: 0,
        contracts: 1,
        date: "2024-05-31",
        id: "23",
        profitLoss: 101.31,
        profitLossPercentage: 100.0,
        realized: "GAIN",
        sellToOpen: 101.31,
        strike: 182.5,
        ticker: "AMZN",
        type: "SELL_CALL",
    },
    {
        buyToClose: 0,
        contracts: 1,
        date: "2024-06-14",
        id: "24",
        profitLoss: 149.31,
        profitLossPercentage: 100.0,
        realized: "GAIN",
        sellToOpen: 149.31,
        strike: 187.5,
        ticker: "AMZN",
        type: "SELL_CALL",
    },
    {
        buyToClose: 10.68,
        contracts: 1,
        date: "2024-06-21",
        id: "25",
        profitLoss: 35.63,
        profitLossPercentage: 76.94,
        realized: "GAIN",
        sellToOpen: 46.31,
        strike: 187.5,
        ticker: "AMZN",
        type: "SELL_CALL",
    },
    {
        buyToClose: 0,
        contracts: 1,
        date: "2024-07-26",
        id: "26",
        profitLoss: 137.31,
        profitLossPercentage: 100.0,
        realized: "GAIN",
        sellToOpen: 137.31,
        strike: 187.5,
        ticker: "AMZN",
        type: "SELL_CALL",
    },
    {
        buyToClose: 0,
        contracts: 1,
        date: "2024-08-02",
        id: "27",
        profitLoss: 239.31,
        profitLossPercentage: 100.0,
        realized: "GAIN",
        sellToOpen: 239.31,
        strike: 200,
        ticker: "AMZN",
        type: "SELL_CALL",
    },
    {
        buyToClose: 0,
        contracts: 4,
        date: "2024-06-14",
        id: "28",
        profitLoss: 49.28,
        profitLossPercentage: 100.0,
        realized: "GAIN",
        sellToOpen: 12.32,
        strike: 27,
        ticker: "MARA",
        type: "SELL_CALL",
    },
    {
        buyToClose: 0,
        contracts: 10,
        date: "2024-06-28",
        id: "29",
        profitLoss: 133.22,
        profitLossPercentage: 100.0,
        realized: "GAIN",
        sellToOpen: 13.32,
        strike: 26,
        ticker: "MARA",
        type: "SELL_CALL",
    },
    {
        buyToClose: 0,
        contracts: 10,
        date: "2024-07-19",
        id: "30",
        profitLoss: 103.22,
        profitLossPercentage: 100.0,
        realized: "GAIN",
        sellToOpen: 10.32,
        strike: 31,
        ticker: "MARA",
        type: "SELL_CALL",
    },
    {
        buyToClose: 0,
        contracts: 10,
        date: "2024-08-30",
        id: "31",
        profitLoss: 143.22,
        profitLossPercentage: 100.0,
        realized: "GAIN",
        sellToOpen: 14.32,
        strike: 20,
        ticker: "MARA",
        type: "SELL_CALL",
    },
    {
        buyToClose: 4.67,
        contracts: 3,
        date: "2024-08-30",
        id: "32",
        profitLoss: 388.92,
        profitLossPercentage: 96.52,
        realized: "GAIN",
        sellToOpen: 134.31,
        strike: 150,
        ticker: "NVDA",
        type: "SELL_CALL",
    },
    {
        buyToClose: 0,
        contracts: 2,
        date: "2024-06-14",
        id: "33",
        profitLoss: 198.64,
        profitLossPercentage: 100.0,
        realized: "GAIN",
        sellToOpen: 99.32,
        strike: 195,
        ticker: "TSLA",
        type: "SELL_CALL",
    },
    {
        buyToClose: 1.67,
        contracts: 2,
        date: "2024-07-12",
        id: "34",
        profitLoss: 283.29,
        profitLossPercentage: 98.83,
        realized: "GAIN",
        sellToOpen: 143.32,
        strike: 285,
        ticker: "TSLA",
        type: "SELL_CALL",
    },
    {
        buyToClose: 0,
        contracts: 2,
        date: "2024-07-26",
        id: "35",
        profitLoss: 192.64,
        profitLossPercentage: 100.0,
        realized: "GAIN",
        sellToOpen: 96.32,
        strike: 300,
        ticker: "TSLA",
        type: "SELL_CALL",
    },
    {
        buyToClose: 0,
        contracts: 2,
        date: "2024-09-13",
        id: "36",
        profitLoss: 300.63,
        profitLossPercentage: 100.0,
        realized: "GAIN",
        sellToOpen: 150.31,
        strike: 250,
        ticker: "TSLA",
        type: "SELL_CALL",
    },
    {
        buyToClose: 1.84,
        contracts: 2,
        date: "2024-09-27",
        id: "37",
        profitLoss: 120.63,
        profitLossPercentage: 97.04,
        realized: "GAIN",
        sellToOpen: 62.155,
        strike: 265,
        ticker: "TSLA",
        type: "SELL_CALL",
    },
    {
        buyToClose: 0,
        contracts: 1,
        date: "2024-05-24",
        id: "38",
        profitLoss: 183.31,
        profitLossPercentage: 100.0,
        realized: "GAIN",
        sellToOpen: 183.31,
        strike: 160,
        ticker: "AMD",
        type: "SELL_PUT",
    },
    {
        buyToClose: 112.67,
        contracts: 2,
        date: "2024-07-19",
        id: "39",
        profitLoss: 91.29,
        profitLossPercentage: 28.83,
        realized: "GAIN",
        sellToOpen: 158.32,
        strike: 190,
        ticker: "AMZN",
        type: "SELL_PUT",
    },
    {
        buyToClose: 27.68,
        contracts: 2,
        date: "2024-05-17",
        id: "40",
        profitLoss: 553.26,
        profitLossPercentage: 90.9,
        realized: "GAIN",
        sellToOpen: 304.31,
        strike: 165,
        ticker: "COIN",
        type: "SELL_PUT",
    },
    {
        buyToClose: 0,
        contracts: 2,
        date: "2024-06-28",
        id: "41",
        profitLoss: 198.64,
        profitLossPercentage: 100.0,
        realized: "GAIN",
        sellToOpen: 99.32,
        strike: 118,
        ticker: "NVDA",
        type: "SELL_PUT",
    },
    {
        buyToClose: 4.68,
        contracts: 1,
        date: "2024-07-19",
        id: "42",
        profitLoss: 184.63,
        profitLossPercentage: 97.53,
        realized: "GAIN",
        sellToOpen: 189.31,
        strike: 117,
        ticker: "NVDA",
        type: "SELL_PUT",
    },
    {
        buyToClose: 2.05,
        contracts: 1,
        date: "2024-06-21",
        id: "43",
        profitLoss: 84.88,
        profitLossPercentage: 97.64,
        realized: "GAIN",
        sellToOpen: 86.93,
        strike: 170,
        ticker: "AMD",
        type: "SELL_CALL",
    },
    {
        buyToClose: 0,
        contracts: 1,
        date: "2024-06-14",
        id: "44",
        profitLoss: 212.93,
        profitLossPercentage: 100.0,
        realized: "GAIN",
        sellToOpen: 212.93,
        strike: 175,
        ticker: "AMD",
        type: "SELL_CALL",
    },
    {
        buyToClose: 5.68,
        contracts: 1,
        date: "2024-06-07",
        id: "45",
        profitLoss: 113.63,
        profitLossPercentage: 95.24,
        realized: "GAIN",
        sellToOpen: 119.31,
        strike: 165,
        ticker: "TSLA",
        type: "SELL_PUT",
    },
    {
        buyToClose: 1.05,
        contracts: 1,
        date: "2024-06-07",
        id: "46",
        profitLoss: 73.88,
        profitLossPercentage: 98.59,
        realized: "GAIN",
        sellToOpen: 74.93,
        strike: 190,
        ticker: "AMD",
        type: "SELL_CALL",
    },
    {
        buyToClose: 1.05,
        contracts: 1,
        date: "2024-05-24",
        id: "47",
        profitLoss: 68.88,
        profitLossPercentage: 98.49,
        realized: "GAIN",
        sellToOpen: 69.93,
        strike: 185,
        ticker: "AMD",
        type: "SELL_CALL",
    },
    {
        buyToClose: 3.05,
        contracts: 1,
        date: "2024-05-10",
        id: "48",
        profitLoss: 64.88,
        profitLossPercentage: 95.51,
        realized: "GAIN",
        sellToOpen: 67.93,
        strike: 150,
        ticker: "AMD",
        type: "SELL_PUT",
    },
    {
        buyToClose: 10.047,
        contracts: 10,
        date: "2024-05-03",
        id: "49",
        profitLoss: 99.02,
        profitLossPercentage: 49.63,
        realized: "GAIN",
        sellToOpen: 19.949,
        strike: 15,
        ticker: "MARA",
        type: "SELL_PUT",
    },
    {
        buyToClose: 17.05,
        contracts: 1,
        date: "2024-04-26",
        id: "50",
        profitLoss: 486.88,
        profitLossPercentage: 96.62,
        realized: "GAIN",
        sellToOpen: 503.93,
        strike: 145,
        ticker: "TSLA",
        type: "SELL_PUT",
    },
    {
        buyToClose: 0,
        contracts: 10,
        date: "2024-01-19",
        id: "51",
        profitLoss: 999.49,
        profitLossPercentage: 100.0,
        realized: "GAIN",
        sellToOpen: 99.949,
        strike: 22,
        ticker: "MARA",
        type: "SELL_PUT",
    },
]
