import { z } from "zod"

// const LINK_VALUES = [1, 2, 3, 4, 5, 6] as const

// const LINK_MARKERS = [
//     ["Bottom"],
//     ["Bottom-Left", "Bottom-Right"],
//     ["Top", "Left", "Bottom", "Right"],
//     ["Left", "Bottom-Left", "Bottom-Right", "Right"],
//     ["Top", "Bottom"],
//     ["Left", "Bottom", "Right", "Top"],
//     ["Bottom", "Right"],
//     ["Left", "Bottom"],
//     ["Bottom", "Bottom-Right", "Right"],
//     ["Left", "Bottom", "Bottom-Right", "Right"],
//     ["Bottom-Left", "Right"],
//     ["Bottom-Left", "Bottom", "Bottom-Right", "Top"],
//     ["Bottom-Left", "Bottom"],
//     ["Top-Right"],
//     ["Top", "Bottom-Left", "Bottom-Right"],
//     ["Top"],
//     ["Bottom-Left", "Bottom", "Bottom-Right"],
//     ["Bottom", "Top"],
//     ["Top", "Left", "Right"],
//     ["Top", "Top-Right", "Bottom-Right"],
//     ["Left", "Right"],
//     ["Bottom-Left", "Top", "Bottom-Right"],
//     ["Top", "Left", "Bottom-Left", "Bottom-Right", "Right"],
//     ["Top", "Right", "Bottom-Right", "Bottom"],
//     ["Top", "Left", "Bottom-Left", "Bottom"],
//     ["Top", "Bottom-Right"],
//     ["Bottom", "Bottom-Right"],
//     ["Top", "Bottom", "Right"],
//     ["Bottom-Left", "Bottom-Right", "Top"],
//     ["Top-Left", "Left", "Bottom-Left", "Bottom", "Bottom-Right"],
//     ["Left"],
//     ["Bottom-Right", "Bottom-Left"],
//     ["Bottom-Right", "Bottom", "Bottom-Left"],
//     ["Top", "Bottom", "Bottom-Right"],
//     ["Left", "Bottom", "Right"],
//     ["Top", "Left", "Bottom-Left", "Bottom-Right", "Right"],
//     ["Left", "Bottom-Left", "Bottom-Right", "Right", "Top"],
//     ["Top-Left", "Left", "Bottom", "Right", "Top-Right", "Top"],
//     ["Left", "Bottom-Left", "Bottom", "Bottom-Right", "Right"],
//     ["Left", "Bottom-Right"],
//     ["Left", "Right", "Bottom"],
//     ["Bottom-Left", "Bottom", "Top"],
//     ["Left", "Bottom", "Top"],
//     ["Bottom-Left"],
//     ["Bottom-Left", "Bottom-Right", "Bottom"],
//     ["Right"],
//     ["Bottom-Left", "Bottom-Right", "Right"],
//     ["BottomRight"],
//     ["Left", "Top"],
//     ["Left", "Top", "Right", "Bottom"],
//     ["Left", "Bottom", "Right"],
//     ["Top", "Right"],
//     ["Left", "Bottom-Left"],
//     ["Top-Left", "Left", "Bottom-Left", "Bottom-Right"],
//     ["Bottom-Right", "Top-Left", "Top"],
//     ["Left", "Bottom-Right", "Bottom", "Right"],
//     ["Left", "Bottom", "Bottom-Right"],
//     ["Top-Right", "Top"],
//     ["Left", "Top", "Right"],
//     ["Top", "Top-Right", "Bottom-Left", "Bottom"],
//     ["Right", "Top-Right"],
//     ["Left", "Bottom-Left", "Right"],
//     ["Right", "Bottom"],
//     ["Left", "Right", "Top"],
//     ["Bottom-Right", "Right"],
//     ["Top-Left", "Bottom-Left", "Bottom-Right"],
//     ["Bottom-Left", "Bottom", "Bottom-Right", "Right"],
//     ["Top-Left", "Top", "Top-Right"],
//     ["Bottom-Right"],
//     ["Top", "Bottom-Left", "Bottom", "Bottom-Right"],
//     ["Top-Left", "Bottom"],
//     ["Top", "Left", "Bottom"],
//     ["Top-Left", "Bottom-Right"],
//     ["Bottom-Left", "Top-Right"],
//     ["Top-Left"],
//     ["Top-Right", "Bottom-Right"],
//     ["BottomLeft"],
//     ["Top", "Right", "Bottom", "Left"],
//     ["Top", "Top-Right", "Bottom-Right", "Bottom"],
//     ["Top", "Left", "Bottom-Left", "Bottom", "Bottom-Right", "Right"],
//     ["Top", "Left", "Right", "Bottom"],
//     ["Top-Left", "Bottom-Left", "Bottom-Right", "Top-Right"],
//     ["Top", "Right", "Bottom"],
//     ["Top", "Right", "Bottom-Left", "Bottom"],
//     ["Bottom-Left", "Right"],
//     ["Bottom", "Bottom-Right", "Right", "Top-Right", "Top"],
//     ["Top", "Left"],
//     ["Bottom-Left", "Top", "Right"],
// ] as const

export const LinkValueSchema = z.union(
    [z.literal(1), z.literal(2), z.literal(3), z.literal(4), z.literal(5), z.literal(6)],
    { message: "Link Value Must Be Between 1 and 6" },
)

export const LinkMarkersSchema = z.array(
    z
        .string()
        .min(1, "Link Marker Must Be At Least 1 Character Long")
        .max(22, "Link Marker Must Be At Most 22 Characters Long"),
)
