export const RAPID_API_KEY = process.env.NEXT_PUBLIC_RAPID_API_KEY
export const BACKEND_BASE_URL = process.env.NEXT_PUBLIC_BACKEND_BASE_URL
export const SUPABASE_REF_ID = process.env.NEXT_PUBLIC_SUPABASE_REF_ID
export const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL
export const SUPABASE_ANON_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY
export const GOOGLE_TAG_MANAGER_ID = process.env.NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID
